services:
  - type: web
    name: aine-movies-hd
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn src.main:app --worker-class eventlet
    pythonVersion: "3.9"
    envVars:
      - key: SECRET_KEY
        value: "your-secret-key-change-this"
